Overlapping in drawio
np-guard/vpc-network-config-analyzer pull request #104
Opened 2023-07-13 15:58 UTC by haim-kermany

overlapping

2023-07-17 13:09 UTC, zivnevo requested changes
Great code!
See some comments.

2023-07-17 13:09 UTC, zivnevo commented on pkg/drawio/layoutOverlap.go
> +			for {
```suggestion
			for { // add bypass points until there is no overlap with icons (or until no bypass can be found)
```

2023-07-17 14:49 UTC, haim-kermany commented on pkg/drawio/layoutOverlap.go
> +	return pow(a, b-1) * a
done

2023-07-17 14:49 UTC, haim-kermany commented on pkg/drawio/layoutOverlap.go
> +	hasBP bool
done

2023-07-17 14:49 UTC, haim-kermany commented on pkg/drawio/layoutOverlap.go
> +var NOPOINT = point{-1, -1}
done

2023-07-17 15:09 UTC, haim-kermany commented on pkg/drawio/layoutOverlap.go
> +			BP = point{BP.X + minSize, BP.Y + minSize}
fixed

2023-07-17 15:11 UTC, haim-kermany commented on pkg/drawio/layoutOverlap.go
> +	absPoints = append(absPoints, iconCenterPoint(line.Src()))
done

2023-07-17 15:16 UTC, haim-kermany commented on pkg/drawio/layoutOverlap.go
> +// getBypassPoint() select the best BS, the closest the has minimal overlapping
fixed

2023-07-17 15:36 UTC, haim-kermany commented on pkg/drawio/layoutOverlap.go
> +	}
yes.
after choosing the BP, we handle the BP->dst interval. so if there is an overlap on BP->dst interval, we will solve it later.
but overlap in src->BP will stay there.

2023-07-18 06:00 UTC, zivnevo commented on pkg/drawio/layoutOverlap.go
> +	}
ok, got it.

2023-07-18 06:07 UTC, haim-kermany commented on pkg/drawio/treeNodeInterface.go
> +func absoluteGeometry(tn TreeNodeInterface) (x, y int) {
kacha

2023-07-18 07:47 UTC, haim-kermany commented on pkg/drawio/layoutOverlap.go
> +			}
fixed

2023-07-18 09:07 UTC, zivnevo submitted a review, later dismissed

2023-07-18 10:48 UTC, zivnevo approved these changes

2023-07-18 10:50 UTC, merged