124 all subnets grouping subnets
np-guard/vpc-network-config-analyzer pull request #142
Opened 2023-08-17 11:20 UTC by ShiriMoran

2023-08-17 11:51 UTC, ShiriMoran commented
Tests for all-subnets + grouping should be added, https://github.com/np-guard/vpc-network-config-analyzer/issues/127

2023-08-21 10:01 UTC, zivnevo requested changes
Some minimal tests are missing here.
Otherwise, looks good.

2023-08-21 12:59 UTC, ShiriMoran commented
> Some minimal tests are missing here. Otherwise, looks good.

I've added a very basic test of sg_testing1_new with  for all_subnets with grouping 
I'll add more tests soon https://github.com/np-guard/vpc-network-config-analyzer/issues/127

2023-08-21 13:28 UTC, zivnevo approved these changes

2023-08-21 14:31 UTC, merged