subnet-grouping2
np-guard/vpc-network-config-analyzer pull request #245
Opened 2023-11-29 10:18 UTC by haim-kermany

git did not agree with the previews one.
Adi, please review the vpcmodel\ibmvpc parts

2023-12-04 14:04 UTC, zivnevo requested changes
Some comments before I start looking into `layout.go` and `subnetsLayout.go`

2023-12-06 12:18 UTC, ShiriMoran reviewed
@haim-kermany I've put some initial comments. Will still need to take it off line to get some basic understanding.

2023-12-06 12:18 UTC, ShiriMoran commented on pkg/vpcmodel/drawioOutput.go
> +		if subnetsConn != nil {
Why is this check, of comparing to nil, required here? It is not performed in the other formats.

2023-12-07 08:06 UTC, haim-kermany commented on pkg/drawio/squareTreeNode.go
> +func GroupedSubnetsSquare(parent *VpcTreeNode, groupedSubnets []SquareTreeNodeInterface) SquareTreeNodeInterface {
in cases the TN is not always generated, the name is not New*TreeNode.
in this case, GroupedSubnetsSquare() might return an existing square
please notice that GroupedSubnetsSquare() calles newGroupSubnetsSquareTreeNode()

2023-12-07 08:06 UTC, haim-kermany commented on .github/workflows/golangci-lint.yml
> +          go-version: "1.20"
fixed

2023-12-07 08:06 UTC, haim-kermany commented on .github/workflows/go-test.yml
> +        go-version: "1.20"
fixed

2023-12-07 10:48 UTC, haim-kermany commented on pkg/vpcmodel/drawioOutput.go
> +		if !n.IsExternal() && (!d.subnetMode || n.ShowOnSubnetMode()) {
they are created on the fly, during the creation of the edges

2023-12-07 10:48 UTC, haim-kermany commented on pkg/vpcmodel/drawioGenerator.go
> +	ShowOnSubnetMode() bool
some return false, see ibmDrawioGenerator.go

2023-12-07 12:43 UTC, haim-kermany commented on pkg/vpcmodel/drawioOutput.go
> +		return &SingleAnalysisOutput{}, errors.New("DebugSubnet use case not supported for draw.io format currently ")
fixed

2023-12-07 12:43 UTC, haim-kermany commented on pkg/vpcmodel/drawioOutput.go
> +		if !d.subnetMode || ns.ShowOnSubnetMode() {
done

2023-12-07 12:44 UTC, haim-kermany commented on pkg/vpcmodel/drawioOutput.go
> +func (d *DrawioOutputFormatter) writeOutputGeneric(cConfig *VPCConfig, conn *GroupConnLines, outFile string, subnetMode bool) (
done

2023-12-07 12:51 UTC, haim-kermany commented on pkg/drawio/lineTreeNode.go
> +		src.(*GroupPointTreeNode).setColleague(dst.(IconTreeNodeInterface))
its guaranteed that GroupingPoints are connected to icons

2023-12-07 12:52 UTC, haim-kermany commented on pkg/drawio/squareTreeNode.go
> +	SubnetMode    bool
fixed

2023-12-07 16:09 UTC, haim-kermany commented on pkg/vpcmodel/drawioOutput.go
> +func (d *DrawioOutputFormatter) writeOutputGeneric(cConfig *VPCConfig, conn *GroupConnLines, outFile string, subnetMode bool) (
fixed

2023-12-07 16:09 UTC, haim-kermany commented on pkg/drawio/createMapFile.go
>  // 3. we put the sgs in the bottom. if a sg is above a square, it will block the the tooltip of the children of the square.
pushed

2023-12-07 16:10 UTC, haim-kermany commented on pkg/drawio/layout.go
> +func (ly *layoutS) resolveGroupedSubnetsOverride() {
fixed

2023-12-10 10:17 UTC, haim-kermany commented on pkg/drawio/subnetsLayout.go
> +	c := genericSet[T]{}
done

2023-12-10 10:18 UTC, haim-kermany commented on pkg/drawio/subnetsLayout.go
moved to common package

2023-12-11 16:13 UTC, zivnevo requested changes
A few more

2023-12-11 16:13 UTC, zivnevo commented on pkg/drawio/subnetsLayout.go
> +
```suggestion
type subnetSet = common.GenericSet[TreeNodeInterface]
type groupTnSet = common.GenericSet[TreeNodeInterface]
type groupSet = common.GenericSet[*groupDataS]
type miniGroupSet = common.GenericSet[*miniGroupDataS]
type setAsKey = common.SetAsKey
```

2023-12-12 08:54 UTC, haim-kermany commented on pkg/common/genericSet.go
> +}
OK
minor comment:
pointers that are not garbage-collected, are not reused

2023-12-12 10:20 UTC, ShiriMoran commented on pkg/vpcmodel/drawioOutput.go
> +	subnetMode bool
indeed

2023-12-12 10:22 UTC, ShiriMoran commented on pkg/vpcmodel/drawioGenerator.go
> +	ShowOnSubnetMode() bool
right

2023-12-12 11:31 UTC, haim-kermany commented on pkg/common/genericSet.go
> +}
fixed, 
I removed interfaceIndex.
instead, I use sprintf to convert a pointer to a string

2023-12-12 11:32 UTC, haim-kermany commented on pkg/drawio/subnetsLayout.go
> +}
done

2023-12-12 11:32 UTC, haim-kermany commented on pkg/common/genericSet.go
> +func (s *GenericSet[T]) AsKey() SetAsKey {
done

2023-12-12 11:32 UTC, haim-kermany commented on pkg/drawio/subnetsLayout.go
> +
done
works, Tnx

2023-12-12 17:05 UTC, haim-kermany commented on pkg/common/genericSet.go
> +}
fixed, using reflact() to get the pointer

2024-01-01 13:45 UTC, zivnevo approved these changes
ok to merge

2024-01-01 14:09 UTC, merged