add info message just when needed
np-guard/vpc-network-config-analyzer pull request #297
Opened 2023-12-26 15:10 UTC by olasaadi99

shortest solution

2023-12-26 15:52 UTC, adisos requested changes
looks good, added an initial comment.. you can now update the expected test output files and verify the resulting output reports, to make sure the info message is indeed added when relevant.

2023-12-26 15:52 UTC, adisos commented on pkg/vpcmodel/grouping.go
> +func (g *GroupConnLines) String() (string, bool) {
few of the `String()` functions here are modified to return `(string, bool)` for indication of the statefuleness property.. let's instead try to split to another function such as `HasUnidirectionalConns()` or `HasStatelessConns()` returning this `bool` value, and keep the `String()` function return only `string`

2023-12-27 09:27 UTC, adisos requested changes
a few small comments

2023-12-27 09:27 UTC, adisos commented on pkg/vpcmodel/grouping.go
> +// get the grouped connectivity stateLessness
```suggestion
// get indication if the connections contain a stateless connection
```

2023-12-27 09:27 UTC, adisos commented on pkg/vpcmodel/grouping.go
> +func (g *GroupConnLines) HasStatelessConns() bool {
the function is called only within this pkg, so should not be exported (rename to `hasStatelessConns`).. same for the `string()` function

2023-12-27 09:27 UTC, adisos commented on pkg/vpcmodel/debugOutput.go
> +	unStateFul := false
rename `unStateFul` to `hasStatelessConns`

2023-12-27 09:27 UTC, adisos commented on pkg/vpcmodel/grouping.go
> +	unStateFul := false
same here (renaming `unStateFul`)

2023-12-27 09:27 UTC, adisos commented on pkg/vpcmodel/mdOutput.go
> +	unStateFul := false
same here

2023-12-27 09:27 UTC, adisos commented on pkg/vpcmodel/output.go
> +	HaveUnStateFulConn bool
```suggestion
        // hasStatelessConn indicates if the connectivity results contain a stateless conn
	hasStatelessConn bool
```

2023-12-27 09:27 UTC, adisos commented on pkg/vpcmodel/semanticDiff.go
> +func (diffCfgs *diffBetweenCfgs) HasStatelessConns() bool {
func should not be exported

2023-12-27 09:27 UTC, adisos commented on pkg/vpcmodel/subnetsConnectivity.go
> +func (v *VPCsubnetConnectivity) HasStatelessConns() bool {
func should not be exported

2023-12-27 09:27 UTC, adisos commented on pkg/vpcmodel/subnetsConnectivity.go
> +	unStateFul := false
same comment about renaming `unStateFul`

2023-12-27 09:27 UTC, adisos commented on pkg/vpcmodel/textOutput.go
> +	unStateFul := false
same comment about renaming `unStateFul`

2023-12-27 14:58 UTC, haim-kermany approved these changes
looks fine with me

2024-01-10 11:02 UTC, adisos requested changes

2024-01-10 11:02 UTC, adisos commented on pkg/vpcmodel/output.go
> +				infoMessage = asteriskDetails
add a function that returns the value of `infoMessage`,  to be used in both places on this file (instead of having similar code in both places).

2024-01-10 14:41 UTC, haim-kermany reviewed
Please notice that a big change  in output.go was merged to the main branch today.
please merge from main to your branch

2024-01-14 13:17 UTC, adisos requested changes

2024-01-14 13:17 UTC, adisos commented on pkg/vpcmodel/output.go
> +		infoMessage = getAsteriskDetails(uc, output.hasStatelessConn, of.outFormat)
```suggestion
		infoMessage := getAsteriskDetails(uc, output.hasStatelessConn, of.outFormat)
```

2024-01-14 13:17 UTC, adisos commented on pkg/vpcmodel/output.go
> +func getAsteriskDetails(uc OutputUseCase, hasStatelessConn bool, outFormat OutFormat) string {
```suggestion
// getAsteriskDetails returns the info message about how non stateful conns are marked in the output, when relevant
func getAsteriskDetails(uc OutputUseCase, hasStatelessConn bool, outFormat OutFormat) string {
```

2024-01-14 13:42 UTC, adisos approved these changes

2024-01-14 13:44 UTC, merged