connect explainConnectivity to main cli
np-guard/vpc-network-config-analyzer pull request #326
Opened 2024-01-16 14:02 UTC by olasaadi99

2024-01-17 10:26 UTC, olasaadi99 commented on cmd/analyzer/main.go
> +
I did change the function.. ExplainConnectivity does not return a string, it returns a struct
and I do the prtinting in the outputFotmatter

2024-01-17 11:37 UTC, ShiriMoran commented on cmd/analyzer/main.go
> +
Cool, sorry I missed it.
Please insert the other change I mention above. Specifically, please call `ExplainConnectivity` in `NewOutputGenerator `under the relevant case `uc == explainMode`

2024-01-21 08:32 UTC, ShiriMoran requested changes
Looks good. Please see my few comments; also merge with the latest branch

2024-01-21 08:32 UTC, ShiriMoran commented on cmd/analyzer/parse_args.go
> +	if *args.EProtocol == "" {
In `ExplainMode` `Protocol` must be specified. So you should simple issue a corresponding error msg here, regardless of `wereExplainParamsSpecified(...)`

2024-01-21 08:32 UTC, ShiriMoran commented on pkg/vpcmodel/nodesExplainability.go
> +func TranslateCDtoConnectionSet(protocol string, srcMinPort, srcMaxPort, dstMinPort, dstMaxPort int64) *common.ConnectionSet {
This is used only in the same package. No need to export (upper case)

2024-01-21 08:32 UTC, ShiriMoran commented on pkg/vpcmodel/output.go
>  	if !diffAnalysis {
ExplainMode also has single vpc input

2024-01-21 09:50 UTC, ShiriMoran requested changes
Please add end-to-end test with conn queried

2024-01-21 09:50 UTC, ShiriMoran commented on cmd/analyzer/parse_args.go
> +			return fmt.Errorf("%s, %s, %s and %s can be specified only when specifying %s",
```suggestion
			return fmt.Errorf("Protocol must be specified when querying a specific connection,",
```

2024-01-21 09:50 UTC, ShiriMoran commented on cmd/analyzer/parse_args.go
> +				ESrcMinPort, ESrcMaxPort, EDstMinPort, EDstMaxPort, EProtocol)
```suggestion)
```

2024-01-21 11:54 UTC, adisos requested changes

2024-01-21 11:54 UTC, adisos commented on cmd/analyzer/parse_args.go
> +	EDstMaxPort           = "e-dst-max-port"
suggest renaming cli args, remove prefix "e-", for example "src" instead of "e-src"

2024-01-21 11:54 UTC, adisos commented on pkg/vpcmodel/nodesExplainability.go
> +		connection.AddICMPConnection(common.MinICMPtype, common.MaxICMPtype,
add a todo comment to later handle also input ICMP properties (type, code) as input args

2024-01-21 11:54 UTC, adisos commented on pkg/vpcmodel/nodesExplainability.go
> +func translateCDtoConnectionSet(protocol string, srcMinPort, srcMaxPort, dstMinPort, dstMaxPort int64) *common.ConnectionSet {
- this function can have one input arg of type `ExplanationArgs` instead
- rename function to follow go naming conventions

2024-01-21 11:54 UTC, adisos commented on pkg/ibmvpc/analysis_output_test.go
> +		ESrcMaxPort: 5,
is it valid to specify input ports without protocol?

2024-01-21 11:54 UTC, adisos commented on pkg/ibmvpc/analysis_output_test.go
> +	}
```suggestion
```
redundant, this var is initialized to `nil` by default

2024-01-21 14:24 UTC, adisos submitted a review, later dismissed

2024-01-21 15:48 UTC, ShiriMoran commented on pkg/vpcmodel/output.go
> +	if !diffAnalysis && uc != Explain {
This is a bit ugly; please add a name for `uc == Explain` or, even better, have one name for both diffAnalysis and explainMode e.g.

` singleVPCAnalysis := (uc == EndpointsDiff || uc == SubnetsDiff) || uc == Explain`

2024-01-21 15:48 UTC, ShiriMoran approved these changes

2024-01-21 17:03 UTC, adisos approved these changes

2024-01-22 06:10 UTC, merged