Extend tgw support prefix filters
np-guard/vpc-network-config-analyzer pull request #329
Opened 2024-01-18 08:43 UTC by adisos

2024-01-18 10:22 UTC, zivnevo reviewed
I think we need a json example from the resource-collector that contains prefix filters. Currently the new parsing code is not exercised in testing.

2024-01-18 11:16 UTC, adisos commented
> I think we need a json example from the resource-collector that contains prefix filters, just to make sure we work correctly with real input.

Indeed, this is in a separate item on the issue description.

2024-01-18 11:21 UTC, zivnevo commented
> > I think we need a json example from the resource-collector that contains prefix filters, just to make sure we work correctly with real input.
> 
> Indeed, this is in a separate item on the issue description.

ah, ok. I was too lazy to go to the issue :zany_face:

2024-01-18 12:16 UTC, zivnevo requested changes

2024-01-18 12:16 UTC, zivnevo commented on pkg/ibmvpc/parser.go
> +	// currently skipping nodes other than network interface (e.g. reserved ip, iks nodes)
Why? Should there be a TODO here? A new task in the issue?

2024-01-18 12:16 UTC, zivnevo commented on pkg/ibmvpc/parser.go
> +	return nodes, nodeSets, err
```suggestion
	return nodes, nodeSets, nil
```
More explicit...

2024-01-18 12:38 UTC, adisos commented on pkg/ibmvpc/tgw_analysis.go
> +	// TOTO: currently ignoring the "Before" field of each PrefixFilter, since assuming the array is ordered
The documentation for the `PrefixFilters` field mentions the array is ordered:
```
// Array of prefix route filters for a transit gateway connection. This is order dependent with those first in the
// array being applied first, and those at the end of the array is applied last, or just before the default.
```

2024-01-18 12:53 UTC, zivnevo commented on pkg/ibmvpc/tgw_analysis.go
> +	// TOTO: currently ignoring the "Before" field of each PrefixFilter, since assuming the array is ordered
OK. Makes sense. I guess we better validate that on the example we get from the cloud-resource-collector.

2024-01-18 16:01 UTC, adisos commented on pkg/ibmvpc/tgw_analysis_test.go
> +						Le:     &le,
added tests

2024-01-22 07:10 UTC, zivnevo approved these changes

2024-01-22 09:32 UTC, merged