creating svg file
np-guard/vpc-network-config-analyzer pull request #419
Opened 2024-02-25 11:03 UTC by haim-kermany

most of the work is:
1. creating a template for svg
2. recode styles.go, and changing drawio template accordingly
3. calculation for svg (see styles.go) 

todo:
reorganize the functions relevant to geometry, and put them together.
will be done in a separate PR

2024-03-04 14:01 UTC, zivnevo requested changes

2024-03-05 10:45 UTC, haim-kermany commented on pkg/drawio/styles.go
> +	errowEndEdge = "block"
fixed

2024-03-05 10:45 UTC, haim-kermany commented on pkg/drawio/createMapFile.go
> +	if false {
yes

2024-03-05 10:47 UTC, haim-kermany commented on pkg/drawio/createMapFile.go
> +		}
in case of true, I want that both drawio and svg formats will be created

2024-03-05 10:47 UTC, haim-kermany commented on pkg/drawio/createMapFile.go
> +	tmpl, err := template.New(tmplName).Parse(templ)
fixed

2024-03-05 10:48 UTC, haim-kermany commented on pkg/drawio/styles.go
> +}
fixed to ''family'

2024-03-05 10:50 UTC, haim-kermany commented
did some more changes:
replace 'Connectivity' with 'Line'
minor change in the connectivity format

2024-03-06 07:24 UTC, zivnevo approved these changes
Code looks good.
Please make sure we also have some testing in the coming PRs

2024-03-06 07:43 UTC, merged