Bump models to v0.3.0
np-guard/vpc-network-config-analyzer pull request #474
Opened 2024-03-21 13:22 UTC by elazarg

2024-03-21 15:09 UTC, zivnevo requested changes

2024-03-21 15:09 UTC, zivnevo commented on pkg/ibmvpc/nacl_analysis.go
> +		conns = connection.TCPorUDPConnection(protocol,
```suggestion
		conns = getTCPUDPConns(*ruleObj.Protocol,
```

2024-03-21 23:11 UTC, elazarg commented on cmd/analyzer/parse_args.go
> +	if protocol != "TCP" && protocol != "UDP" && protocol != "ICMP" {
I did not want to leak the library to the user.

2024-03-24 08:22 UTC, elazarg commented on pkg/ibmvpc/nacl_analysis.go
> +		conns = connection.TCPorUDPConnection(protocol,
Done

2024-03-24 08:22 UTC, elazarg commented on cmd/analyzer/parse_args.go
> +	if protocol != "TCP" && protocol != "UDP" && protocol != "ICMP" {
Done

2024-03-24 08:49 UTC, zivnevo approved these changes

2024-03-24 08:50 UTC, merged