system implicit routing + routing path type
np-guard/vpc-network-config-analyzer pull request #507
Opened 2024-04-09 05:34 UTC by adisos

2024-04-09 11:22 UTC, zivnevo requested changes

2024-04-09 11:22 UTC, zivnevo commented on pkg/ibmvpc/routing_paths.go
Shouldn't this reside in `vpcmodel`? Looks general enough

2024-04-09 11:22 UTC, zivnevo commented on pkg/ibmvpc/routing_paths.go
> +		if !otherEndpoint.nextHop.equal(e.nextHop) {
`otherEndpoint.nextHop` might be nil

2024-04-09 11:22 UTC, zivnevo commented on pkg/ibmvpc/routing_paths.go
> +		e.ipBlock != nil:
```suggestion
	case e.ipBlock != nil:
```

2024-04-09 11:22 UTC, zivnevo commented on pkg/ibmvpc/implicit_routing.go
> +	vpc    *VPC
```suggestion
	vpc    *VPC // parent VPC
```

2024-04-09 16:16 UTC, adisos commented on pkg/ibmvpc/implicit_routing.go
> +type config struct {
right, changed

2024-04-09 16:16 UTC, adisos commented on pkg/ibmvpc/routing_paths.go
> +}
opened PR there: https://github.com/np-guard/models/pull/31

2024-04-09 16:17 UTC, adisos commented on pkg/ibmvpc/routing_paths.go
> +		if !otherEndpoint.nextHop.equal(e.nextHop) {
right, fixed

2024-04-09 16:17 UTC, adisos commented on pkg/ibmvpc/routing_paths.go
> +		e.ipBlock != nil:
done

2024-04-09 16:17 UTC, adisos commented on pkg/ibmvpc/implicit_routing.go
> +	vpc    *VPC
done

2024-04-10 05:27 UTC, adisos commented on pkg/ibmvpc/routing_paths.go
> +}
done

2024-04-10 05:36 UTC, zivnevo approved these changes

2024-04-10 05:42 UTC, merged