803 explain path aws subnet new
np-guard/vpc-network-config-analyzer pull request #831
Opened 2024-08-26 12:44 UTC by ShiriMoran

2024-08-28 09:02 UTC, haim-kermany requested changes
consider code reorg of explainabilityPrint.go

2024-08-28 18:27 UTC, ShiriMoran commented
more examples of explain + aws private subnets needs to be added

> consider code reorg of explainabilityPrint.go

Feel free to open an issue and elaborate more in the issue

2024-08-28 18:29 UTC, ShiriMoran commented on pkg/awsvpc/examples/out/explain_out/to_external_private_subnet_all_vpcs_explain_detail.txt
> +	app1[10.240.20.245] -> | security group GroupName:43 |
1. The SG indeed block egress. I verified against the json file
2. For egress, SG is before the subnet see [here](https://github.com/np-guard/vpc-network-config-analyzer/issues/769)

2024-08-28 18:34 UTC, ShiriMoran commented on pkg/ibmvpc/vpc.go
> +// todo: use detail to get a concise printing for !detail
Its not related to this PR. https://github.com/np-guard/vpc-network-config-analyzer/issues/840 opened

2024-08-28 18:36 UTC, ShiriMoran commented on pkg/commonvpc/vpc.go
> +		return fmt.Sprintf("traffic from %s to %s is allowed, since subnet %s is public\n",
When detail is high then there is a differentiation between egress and ingress.
When  it is low the explanation should be short, without the additional egress/ingress details.

2024-09-01 10:07 UTC, ShiriMoran commented on pkg/commonvpc/vpc.go
> +		return fmt.Sprintf("traffic from %s to %s is allowed, since subnet %s is public\n",
However, a bug regarding subnet in path for external existed and was fixed. Does not change this example; another relevant example added

2024-09-01 12:11 UTC, haim-kermany approved these changes

2024-09-02 13:46 UTC, ShiriMoran commented
closing since contained in #843

2024-09-02 13:46 UTC, closed without merging