support multi-vpc in synthesis output
np-guard/vpc-network-config-analyzer pull request #838
Opened 2024-08-28 12:52 UTC by olasaadi99

2024-08-29 12:15 UTC, kyorav commented
When applied to an example that uses a transit gateway the output contains the string `combined-vpc-local-tg1/` instead of the name of the VPC. Example config object attached (taken from the `transit-gateway-multiple` example)
[config_object.json](https://github.com/user-attachments/files/16798787/config_object.json)

2024-09-02 10:52 UTC, kyorav commented
I tested on several examples and it looks great

2024-09-03 12:23 UTC, zivnevo requested changes

2024-09-03 12:23 UTC, zivnevo commented on pkg/vpcmodel/output.go
> +		}
```suggestion
		if conn.Src.Type == spec.ResourceTypeExternal {
			conn.Src.Name = getNewExternalName(conn.Src.Name, externalsMap)
		} else if conn.Dst.Type == spec.ResourceTypeExternal {
			conn.Dst.Name = getNewExternalName(conn.Dst.Name, externalsMap)
		}
```
Avoid code duplication

2024-09-03 12:23 UTC, zivnevo commented on pkg/vpcmodel/output.go
> +				name := externalString + strconv.Itoa(len(externalsMap))
`fmt.Sprintf()` might be better here

2024-09-04 13:18 UTC, zivnevo approved these changes

2024-09-05 08:12 UTC, merged