support explainability for public node square
np-guard/vpc-network-config-analyzer pull request #857
Opened 2024-09-05 10:23 UTC by haim-kermany

the solution is always to create a "public network" icon.
it is holding the "public network" explainability infornation
if it ha no connection, do not show in on the canvas.

2024-09-09 05:25 UTC, ShiriMoran commented on pkg/vpcmodel/drawioOutput.go
> +// however, we always create it since it's needed for holding the explainability information of the public network square
```suggestion
// createPublicNetworkIcon() - creates the iconTreeNode that represents the Public Network (always)
// it holds the explainability information of the public network square, which may be connected or not connected
// to the internal endpoints
```

2024-09-09 05:37 UTC, ShiriMoran commented on pkg/vpcmodel/multiExplainability.go
> +	if cConfigs.publicNetworkNode != nil {
What is the situation in which it is legit  cConfigs.publicNetworkNode will be nil?
Shouldn't this node be always present?

2024-09-09 11:59 UTC, ShiriMoran reviewed
LGTM
I did not review the `drawio` related files

2024-09-09 11:59 UTC, ShiriMoran commented on pkg/vpcmodel/multi_vpc_config.go
> +	// publicNetworkNode - the EndpointElem that represent all the cidr which are not in ant vpc:
```suggestion
	// publicNetworkNode - the EndpointElem that  entire external cidr which is in any vpc:
```

2024-09-11 09:38 UTC, zivnevo requested changes
A few small things

2024-09-11 09:38 UTC, zivnevo commented on pkg/drawio/connectivityMap.svg.tmpl
In line 233, please change the text to:
`Explaining connectivity from <src> to <dst>`

2024-09-12 05:04 UTC, haim-kermany commented on pkg/drawio/connectivityMap.svg.tmpl
fixed

2024-09-12 05:04 UTC, haim-kermany commented on pkg/vpcmodel/drawioOutput.go
> +			}
fixed

2024-09-12 05:04 UTC, haim-kermany commented on pkg/vpcmodel/drawioOutput.go
> +	if d.cConfigs.publicNetworkNode != nil {
fixed

2024-09-12 06:46 UTC, zivnevo approved these changes

2024-09-12 06:51 UTC, merged