support segments synthesis
np-guard/vpc-network-config-analyzer pull request #870
Opened 2024-09-11 09:04 UTC by olasaadi99

support segments synthesis

2024-09-12 09:40 UTC, olasaadi99 commented
> I created a new example with subnet grouping (folder is called `subnet-grouping`) and ran it as follows:
> 
> ```
> ../../vpc-network-config-analyzer/bin/vpcanalyzer report subnets -c config_object.json -o synthesis -f subnets_synthesis_g.json -g
> ```
> 
> This shows two problems:
> 
> 1. The segments are not added to the output fiIe
segments are added to the out file.. at the end of the file..
will fix other problems

2024-09-12 09:43 UTC, kyorav commented
> segments are added to the out file.. at the end of the file..

They were not added to the out file when I ran it. Should I pull a fresh version of the branch and try again?

2024-09-12 09:45 UTC, olasaadi99 commented
> > segments are added to the out file.. at the end of the file..
> 
> They were not added to the out file when I ran it. Should I pull a fresh version of the branch and try again?

I think you should

2024-09-12 09:57 UTC, olasaadi99 commented
> If I run without `-g` (grouping) then I get `subgrouping/` as a prefix for all subnets:
> 
> ```
> "dst": {
>                 "name": "subgrouping/sub2",
>                 "type": "subnet"
>             }
> ```

it is the name of the vpc... as expected

2024-09-15 10:37 UTC, kyorav commented
> it is the name of the vpc... as expected
of course, my bad

The output with grouping looks great. Without grouping it is too long to check in depth, but I can't see any glaring issues.

2024-09-16 14:36 UTC, zivnevo requested changes
Looks good.
A few small things

2024-09-16 14:36 UTC, zivnevo commented on pkg/vpcmodel/synthesisOutput.go
>  	resourceType spec.ResourceType) {
```suggestion
func handleNameAndType(resource EndpointElem, externals spec.SpecExternals, segments spec.SpecSegments, grouping bool) (
	resourceName string, resourceType spec.ResourceType) {
```
too many lines

2024-09-16 14:36 UTC, zivnevo commented on pkg/vpcmodel/synthesisOutput.go
> +		if structObj, ok := resource.(*groupedEndpointsElems); ok {
```suggestion
		if groupObj, ok := resource.(*groupedEndpointsElems); ok {
```
`structObj` is a bit misleading. The type is a slice of structs, not a struct

2024-09-16 14:36 UTC, zivnevo commented on pkg/vpcmodel/synthesisOutput.go
> +			if structObj.LenOfGroupedEndpoints() > 1 {
```suggestion
			if len(*structObj) > 1 {
```
No need for a dedicated function

2024-09-16 14:36 UTC, zivnevo commented on pkg/vpcmodel/grouping.go
> +func (g *groupedEndpointsElems) GroupedEndpointsElemsNamesList() []string {
```suggestion
func (g *groupedEndpointsElems) AsNamesList() []string {
```
Struct type should not be part of a its method name

2024-09-16 14:36 UTC, zivnevo commented on pkg/vpcmodel/output.go
> +func getNewExternalSegmentName(externalSegmentName, prefixString string, namesMap map[string]string) string {
Move this function to `synthesisOutput.go`

2024-09-16 14:36 UTC, zivnevo commented on pkg/vpcmodel/output.go
> +func renameExternalsSegments(requiredConnections []spec.SpecRequiredConnectionsElem,
Move to `synthesisOutput.go`

2024-09-16 14:36 UTC, zivnevo commented on pkg/vpcmodel/output.go
> +func renameExternalsSegments(requiredConnections []spec.SpecRequiredConnectionsElem,
```suggestion
func renameExternalsAndSegments(requiredConnections []spec.SpecRequiredConnectionsElem,
```

2024-09-16 14:36 UTC, zivnevo commented on pkg/vpcmodel/output.go
> +func getNewExternalSegmentName(externalSegmentName, prefixString string, namesMap map[string]string) string {
```suggestion
func getNewExternalOrSegmentName(externalSegmentName, prefixString string, namesMap map[string]string) string {
```

2024-09-17 12:52 UTC, zivnevo approved these changes

2024-09-18 16:10 UTC, merged